name: tp0
networks:
  bet_network:
    ipam:
      config:
      - subnet: 172.25.126.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    image: client:latest
    networks:
    - bet_network
    volumes:
    - ./client/config.yaml:/config.yaml:ro
    - ./.data/agency-1.csv:/data/agency-1.csv:ro
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - bet_network
    volumes:
    - ./server/config.ini:/config.ini:ro
    - ./.data_server/bets.csv:/bets.csv
