name: tp0
networks:
  bet_network:
    ipam:
      config:
      - subnet: 172.25.126.0/24
      driver: default
services:
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - bet_network
    volumes:
      - ./server/config.ini:/config.ini:ro
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    networks:
      - bet_network
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml:ro
